[build-system]
requires = ["setuptools>=82", "wheel>=0.47"]
build-backend = "setuptools.build_meta"

[project]
name = "t5pKa"
version = "2.0.0rc1"
description = "Reproducible environment for T5Chem or T5pKa"
requires-python = ">=3.11,<3.13"
readme = "README.md"

dependencies = [
    "numpy>=2.4,<3",
    "pandas>=3.0,<4",
    "scipy>=1.17,<2",
    "scikit-learn>=1.8,<2",
    "joblib>=1.5,<2",
    "tqdm>=4.67,<5",
    "torch>=2.12,<3",
    "transformers>=5.8,<6",
    "huggingface_hub>=1.15,<2",
    "accelerate>=1.13,<2",
    "datasets>=4.8,<5",
    "rdkit>=2026.3",
    "h5py>=3.16,<4",
    "matplotlib>=3.10,<4",
    "ipython>=9.13,<10"
]

[project.optional-dependencies]
analysis = [
    "shap>=0.51,<1",
    "EFGs==0.8.4",
    "selfies>=2.2,<3"
]

dev = [
    "pytest>=9,<10",
    "ruff>=0.15,<1",
    "black>=26,<27",
    "ipykernel>=7,<8"
]

[project.scripts]
t5pka = "t5pka.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
